apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-profe-fredy
  template:
    metadata:
      labels:
        app: test-profe-fredy
    spec:
      containers:
        - name: test-profe-fredy
          image: fredyball/testdevopsreact:$(Build.BuildId)
          ports:
            - containerPort: 80